version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  assignees:
  - jungissei
  labels:
  - dependencies
  ignore:
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: jbuilder
    versions:
    - 2.11.1
  - dependency-name: capybara
    versions:
    - 3.34.0
  - dependency-name: devise-i18n
    versions:
    - 1.9.2
